services:
  db:
    image: postgres:18-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py seed_data && gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - SECRET_KEY=django-insecure-local-dev-key
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,web
    depends_on:
      - db

volumes:
  postgres_data:
