# Generated by Django 6.0.3 on 2026-03-06 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('world_rank', models.IntegerField()),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='universities.university')),
            ],
            options={
                'ordering': ['world_rank'],
                'unique_together': {('university', 'year')},
            },
        ),
    ]
