# Generated by Django 6.0.3 on 2026-03-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
